---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Port
metadata:
  name: port
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    networkRef: external-network
    tags:
    - orc-test
    securityGroupRefs:
    - allow-ssh
    - devstack
    - default
    addresses:
    - subnetRef: external-subnet-ipv4
