apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Port
metadata:
  name: orc-managed-port
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    networkRef: orc-managed-network
    description: Blah blah blah
    tags:
      - orc-test
    allowedAddressPairs:
      - ip: 192.168.3.3
        mac: 00:00:00:00:00:01
      - ip: 192.168.4.4
    addresses:
      - subnetRef: orc-managed-subnet
      - ip: 192.168.0.8
        subnetRef: orc-managed-subnet
    securityGroupRefs:
      - orc-managed-sg
