apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: orc-managed-subnet
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    networkRef: orc-managed-network
    description: |
      Blah blah blah
    tags:
    - orc-test
    ipVersion: 4
    cidr: 192.168.0.0/24
