apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: image-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    content:
      diskFormat: qcow2
      download:
        url: https://example.com/image.img
