name: devstack-action
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.gitignore'
      - '**LICENSE'
jobs:
  functional-basic:
    strategy:
      fail-fast: false
      matrix:
        name: ["master"]
        openstack_version: ["master"]
        ubuntu_version: ["22.04"]
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} with defaults and run basic acceptance tests
    steps:
      - name: Deploy devstack
        uses: EmilienM/devstack-action@c41f86d8df58b53c55f070207b6dfce656788cfd
        with:
          branch: ${{ matrix.openstack_version }}
          enabled_services: 's-account,s-container,s-object,s-proxy'
          conf_overrides: |
            # This is a comment with "quotes"
            [[post-config|/etc/neutron/port_binding.yaml]]
            "create_port:binding:profile": "rule:admin_only or rule:service_api"
